/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new buyer or organizer account */
    post: operations['auth.register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange credentials for a bearer token */
    post: operations['auth.login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current bearer token */
    post: operations['auth.logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the authenticated user */
    get: operations['auth.me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published events */
    get: operations['catalog.index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return one published event with its venue */
    get: operations['catalog.show'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events/{id}/seats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the seat map snapshot for an event */
    get: operations['catalog.seats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Place an order for the seats this session holds */
    post: operations['order.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return one of the buyer's own orders */
    get: operations['order.show'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/my/tickets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the buyer's tickets */
    get: operations['order.tickets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/organizer/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a draft event */
    post: operations['organizer.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/organizer/events/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a draft event */
    put: operations['organizer.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/organizer/events/{id}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a draft event */
    post: operations['organizer.publish'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/organizer/events/{id}/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return sales statistics for an event */
    get: operations['organizer.stats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/organizer/check-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Check a ticket in at the door */
    post: operations['organizer.checkIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CheckInRequest */
    CheckInRequest: {
      qr_code: string;
    };
    /** CreateEventRequest */
    CreateEventRequest: {
      venue_id: number;
      title: string;
      description?: string | null;
      /** Format: date-time */
      starts_at: string;
    };
    /** EventDetailResource */
    EventDetailResource: {
      id: number;
      title: string;
      description: string;
      /** Format: date-time */
      starts_at: string;
      status: string;
      venue: components['schemas']['VenueResource'];
    };
    /** EventResource */
    EventResource: {
      id: number;
      title: string;
      /** Format: date-time */
      starts_at: string;
      status: string;
      venue: {
        id: number;
        name: string;
      };
    };
    /** EventStatsResource */
    EventStatsResource: {
      event_id: number;
      seats_total: number;
      seats_sold: number;
      seats_free: number;
      revenue_cents: number;
      currency: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** OrderItemResource */
    OrderItemResource: {
      event_seat_id: number;
      price_cents: number;
    };
    /** OrderResource */
    OrderResource: {
      /** Format: uuid */
      id: string;
      event_id: number;
      status: components['schemas']['OrderStatus'];
      total_cents: number;
      currency: string;
      items: components['schemas']['OrderItemResource'][];
    };
    /**
     * OrderStatus
     * @enum {string}
     */
    OrderStatus:
      'pending' | 'paid' | 'payment_failed' | 'cancelled' | 'expired';
    /** PlaceOrderRequest */
    PlaceOrderRequest: {
      event_id: number;
      seat_ids: number[];
      /** Format: uuid */
      session_id: string;
      idempotency_key: string;
    };
    /** RegisterRequest */
    RegisterRequest: {
      name: string;
      /** Format: email */
      email: string;
      password: string;
      /** @enum {string} */
      role: 'buyer' | 'organizer';
    };
    /** SeatResource */
    SeatResource: {
      id: number;
      section: string;
      row: number;
      number: number;
      x: number;
      y: number;
      price_cents: number;
      currency: string;
      status: string;
    };
    /** TicketResource */
    TicketResource: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      order_id: string;
      event_seat_id: number;
      qr_code: string;
      status: string;
      /** Format: date-time */
      checked_in_at: string | null;
    };
    /** UpdateEventRequest */
    UpdateEventRequest: {
      venue_id: number;
      title: string;
      description?: string | null;
      /** Format: date-time */
      starts_at: string;
    };
    /** UserResource */
    UserResource: {
      id: number;
      name: string;
      email: string;
      role: string;
    };
    /** VenueResource */
    VenueResource: {
      id: number;
      name: string;
      address: string;
      city: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'auth.register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            token: string;
            user: components['schemas']['UserResource'];
          };
        };
      };
      /** @description VALIDATION_FAILED */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'VALIDATION_FAILED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                [key: string]: string[];
              };
            };
          };
        };
      };
    };
  };
  'auth.login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            token: string;
            user: components['schemas']['UserResource'];
          };
        };
      };
      /** @description VALIDATION_FAILED */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'VALIDATION_FAILED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                [key: string]: string[];
              };
            };
          };
        };
      };
    };
  };
  'auth.logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'auth.me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'catalog.index': {
    parameters: {
      query?: {
        page?: number | null;
        per_page?: number | null;
        starts_from?: string | null;
        starts_until?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated set of `EventResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['EventResource'][];
            links: {
              first: string | null;
              last: string | null;
              prev: string | null;
              next: string | null;
            };
            meta: {
              current_page: number;
              from: number | null;
              last_page: number;
              /** @description Generated paginator links. */
              links: {
                url: string | null;
                label: string;
                active: boolean;
              }[];
              /** @description Base path for paginator generated URLs. */
              path: string | null;
              /** @description Number of items shown per page. */
              per_page: number;
              /** @description Number of the last item in the slice. */
              to: number | null;
              /** @description Total number of items being paginated. */
              total: number;
            };
          };
        };
      };
      /** @description VALIDATION_FAILED */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'VALIDATION_FAILED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                [key: string]: string[];
              };
            };
          };
        };
      };
    };
  };
  'catalog.show': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `EventDetailResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventDetailResource'];
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'catalog.seats': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `SeatResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeatResource'][];
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'order.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PlaceOrderRequest'];
      };
    };
    responses: {
      /** @description `OrderResource` */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description PAYMENT_DECLINED */
      402: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'PAYMENT_DECLINED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /**
       * @description SEATS_NOT_HELD
       *
       *     VALIDATION_FAILED
       */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                error: {
                  /** @enum {string} */
                  code: 'SEATS_NOT_HELD';
                  /** @description One human-readable sentence, safe to show a user. */
                  message: string;
                  /** @description Omitted entirely when empty. */
                  details?: {
                    seats: number[];
                  };
                };
              }
            | {
                error: {
                  /** @enum {string} */
                  code: 'VALIDATION_FAILED';
                  /** @description One human-readable sentence, safe to show a user. */
                  message: string;
                  /** @description Omitted entirely when empty. */
                  details?: {
                    [key: string]: string[];
                  };
                };
              };
        };
      };
    };
  };
  'order.show': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `OrderResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'order.tickets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `TicketResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TicketResource'][];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'organizer.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEventRequest'];
      };
    };
    responses: {
      /** @description `EventDetailResource` */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventDetailResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description VALIDATION_FAILED */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'VALIDATION_FAILED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                [key: string]: string[];
              };
            };
          };
        };
      };
    };
  };
  'organizer.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEventRequest'];
      };
    };
    responses: {
      /** @description `EventDetailResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventDetailResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description INVALID_STATE_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'INVALID_STATE_TRANSITION';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                status: string;
              };
            };
          };
        };
      };
      /** @description VALIDATION_FAILED */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'VALIDATION_FAILED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                [key: string]: string[];
              };
            };
          };
        };
      };
    };
  };
  'organizer.publish': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `EventDetailResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventDetailResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description INVALID_STATE_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'INVALID_STATE_TRANSITION';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                status: string;
              };
            };
          };
        };
      };
      /** @description INVALID_SEAT_MAP_TEMPLATE */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'INVALID_SEAT_MAP_TEMPLATE';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'organizer.stats': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `EventStatsResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventStatsResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
    };
  };
  'organizer.checkIn': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CheckInRequest'];
      };
    };
    responses: {
      /** @description `TicketResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TicketResource'];
        };
      };
      /** @description UNAUTHENTICATED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'UNAUTHENTICATED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'FORBIDDEN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'NOT_FOUND';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
            };
          };
        };
      };
      /** @description ALREADY_CHECKED_IN */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'ALREADY_CHECKED_IN';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                /** Format: date-time */
                checked_in_at: string;
              };
            };
          };
        };
      };
      /** @description VALIDATION_FAILED */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code: 'VALIDATION_FAILED';
              /** @description One human-readable sentence, safe to show a user. */
              message: string;
              /** @description Omitted entirely when empty. */
              details?: {
                [key: string]: string[];
              };
            };
          };
        };
      };
    };
  };
}
